### ISSUE TITLE
Error with jenkinsapi version 0.3.12 caused build farm service interruption

### ISSUE THREAD

**Issue by nuclearsandwich** [osrf/infrastructure#14]
- [x] I have checked [ROS Answers](https://answers.ros.org) for similar reports and solutions.
- [x] I have checked the [ROS Status page](https://status.ros.org) and my issue is not listed there.
- [x] I have checked the [open issues](https://github.com/osrf/infrastructure/issues) for similar reports.
- [x] This is **not** a [security issue](https://github.com/osrf/infrastructure/blob/latest/SECURITY.md) If you have a security issue to report please do so via email to <security@openrobotics.org>.

## Problem description

Some release management jobs on build.ros.org and build.ros2.org began failing around 12:00am Pacific time on 2023-01-26 due to a bug (https://github.com/pycontribs/jenkinsapi/issues/833) in the 0.3.12 release of the `jenkinsapi` project on pypi. This release has since been yanked so there is no separate record of its exact contents contents.

The Open Robotics team saw the failure emails and reported the issue internally around 5:40am.

The affected jobs all had failed with python stacktraces similar to:

```
23:01:50 Traceback (most recent call last):
23:01:50   File "/tmp/ros_buildfarm/scripts/release/generate_release_jobs.py", line 21, in <module>
23:01:50     run_module('ros_buildfarm.scripts.release.generate_release_jobs', run_name='__main__')
23:01:50   File "/usr/lib/python3.8/runpy.py", line 210, in run_module
23:01:50     return _run_code(code, {}, init_globals, run_name, mod_spec)
23:01:50   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
23:01:50     exec(code, run_globals)
23:01:50   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/release/generate_release_jobs.py", line 45, in <module>
23:01:50     sys.exit(main())
23:01:50   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/release/generate_release_jobs.py", line 38, in main
23:01:50     return configure_release_jobs(
23:01:50   File "/tmp/ros_buildfarm/ros_buildfarm/release_job.py", line 169, in configure_release_jobs
23:01:50     views = configure_release_views(
23:01:50   File "/tmp/ros_buildfarm/ros_buildfarm/release_job.py", line 569, in configure_release_views
23:01:50     from ros_buildfarm.jenkins import configure_view
23:01:50   File "/tmp/ros_buildfarm/ros_buildfarm/jenkins.py", line 22, in <module>
23:01:50     from jenkinsapi.jenkins import Jenkins
23:01:50   File "/usr/local/lib/python3.8/dist-packages/jenkinsapi/__init__.py", line 50, in <module>
23:01:50     from jenkinsapi import (
23:01:50   File "/usr/local/lib/python3.8/dist-packages/jenkinsapi/api.py", line 15, in <module>
23:01:50     from jenkinsapi.jenkins import Jenkins
23:01:50   File "/usr/local/lib/python3.8/dist-packages/jenkinsapi/jenkins.py", line 18, in <module>
23:01:50     from jenkinsapi.jobs import Jobs
23:01:50   File "/usr/local/lib/python3.8/dist-packages/jenkinsapi/jobs.py", line 7, in <module>
23:01:50     from jenkinsapi.job import Job
23:01:50   File "/usr/local/lib/python3.8/dist-packages/jenkinsapi/job.py", line 23, in <module>
23:01:50     from jenkinsapi_utils.compat import to_string
23:01:50 ModuleNotFoundError: No module named 'jenkinsapi_utils'
```

with jenkinsapi as the likely culprit checking https://pypi.org/project/jenkinsapi/#history revealed what appeared to be the _first_ new release of the project in three years and the timing lined up with the initial report but not with the earliest failures. Also, the contents of the 0.3.13 release did not match the bug that we were seeing.

When investigating the jenkinsapi module as installed in production we found a 0.3.12 release installed which is not listed on either pypi or GitHub and thus assume that the release has since been yanked.

After reviewing jenkinsapi 0.3.13 and concluding it is likely to restore functionality for our jobs without any changes on our end, we decided that the most expedient fix was to purge image caches of the yanked 0.3.12 which had been installed overnight.

On each Jenkins host as a user with docker access:
```
docker image prune -f && docker images -q | xargs docker rmi
```
Pruning will remove stale images but not current ones and xargs breaks with the number of images if prune isn't run first.

After taking these steps build.ros.org and build.ros2.org have been able to run management jobs which use jenkinsapi normally. Jobs which failed over night will be run again on schedule tonight and no additional action is being taken to recover them as of now.

**Comment by nuclearsandwich** [comment]
This was opened in order to document an issue which occurred but I am going to close it directly as it is currently resolved.
