### ISSUE TITLE
ROS 1 doc job failing due to "script not yet approved for use"

### ISSUE THREAD

**Issue by gavanderhoorn** [osrf/infrastructure#4]
[Mdoc__fanuc_experimental__ubuntu_bionic_amd64](https://build.ros.org/job/Mdoc__fanuc_experimental__ubuntu_bionic_amd64/15) failed due to:

```
ERROR: Build step failed with exception
org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.using(ScriptApproval.java:474)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:377)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:314)
	at hudson.plugins.groovy.SystemGroovy.run(SystemGroovy.java:95)
	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:59)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute system Groovy script' marked build as failur
```

This is [right at the end](https://build.ros.org/job/Mdoc__fanuc_experimental__ubuntu_bionic_amd64/15/console#console-section-7), in the *rsync API documentation to server* step.

I've seen this happen before (two weeks ago?) but it appeared to be transient. Perhaps a slave is not up-to-date wrt configuration?

**Comment by gavanderhoorn** [comment]
Other jobs I got emails for:

 - [Ndoc__moveit__ubuntu_focal_amd64](https://build.ros.org/job/Ndoc__moveit__ubuntu_focal_amd64/19)
 - [Ndoc__ur_msgs__ubuntu_focal_amd64](https://build.ros.org/job/Ndoc__ur_msgs__ubuntu_focal_amd64/1)

**Comment by rhaschke** [comment]
@tfoote, @nuclearsandwich: Could you have a look at this issue. There are 193 doc jobs currently failing on https://build.ros.org.

**Comment by nuclearsandwich** [comment]
Thanks for the report. The script was updated in https://github.com/ros-infrastructure/ros_buildfarm/pull/887 and the updated script was never approved. It has now been and jobs are now running successfully. Recently failed Mdoc jobs have been re-triggered and once the build farm settles after that I'll do the Ndoc jobs.

Thanks for raising the issue and escalating. GitHub notifications are still a mess and I'm working on how to float these issues to the top of my queue.
